# Generated by Django 3.0.2 on 2020-01-06 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 16, 58, 24, 411574)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 16, 58, 24, 404095, tzinfo=utc)),
        ),
    ]
