# Generated by Django 3.0.2 on 2020-01-03 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artwork',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 19, 34, 38, 197807)),
        ),
    ]
